version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      DATABASE_URL: "postgres://postgres:user123@db:5432/restaurantapi"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: su -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/restaurantApi
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  postgres_data: